// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-orders.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function textResult(value) {
  return { content: [{ type: "text", text: JSON.stringify(value) }] };
}
function errorResult(message) {
  return {
    content: [{ type: "text", text: message }],
    isError: true
  };
}

// src/lib/mcp/tools/list-orders.ts
var list_orders_default = defineTool({
  name: "list_orders",
  title: "List orders",
  description: "List production orders (order no, style, customer, quantity, dates). Optionally filter by a search term matching order no, style or customer.",
  inputSchema: {
    search: z.string().optional().describe("Text to match in order no, style no, style name or customer."),
    limit: z.number().int().optional().describe("Maximum rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let query = supabaseForUser(ctx).from("orders").select(
      "id, order_no, style_no, style_name, customer, quantity, shade, fabric_type, status, order_date, delivery_date, created_at"
    ).order("created_at", { ascending: false }).limit(Math.min(limit ?? 50, 200));
    if (search?.trim()) {
      const s = `%${search.trim()}%`;
      query = query.or(
        `order_no.ilike.${s},style_no.ilike.${s},style_name.ilike.${s},customer.ilike.${s}`
      );
    }
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult({ orders: data ?? [] });
  }
});

// src/lib/mcp/tools/list-requests.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_requests_default = defineTool2({
  name: "list_requests",
  title: "List material requests",
  description: "List material requests with their approval status, TR number and linked order. Filter by approval status or order id.",
  inputSchema: {
    approval_status: z2.string().optional().describe("One of: pending, approved, not_approved, hold."),
    order_id: z2.string().optional().describe("Only requests for this order id."),
    limit: z2.number().int().optional().describe("Maximum rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ approval_status, order_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let query = supabaseForUser(ctx).from("requests").select("*").order("created_at", { ascending: false }).limit(Math.min(limit ?? 50, 200));
    if (approval_status) query = query.eq("approval_status", approval_status);
    if (order_id) query = query.eq("order_id", order_id);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult({ requests: data ?? [] });
  }
});

// src/lib/mcp/tools/get-request.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_request_default = defineTool3({
  name: "get_request",
  title: "Get request with items",
  description: "Fetch one material request by id or request number, including all of its line items.",
  inputSchema: {
    request_id: z3.string().optional().describe("Request id (uuid)."),
    request_no: z3.string().optional().describe("Request/document number, e.g. RMR-0012.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ request_id, request_no }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    if (!request_id && !request_no)
      return errorResult("Provide either request_id or request_no.");
    const client = supabaseForUser(ctx);
    let query = client.from("requests").select("*").limit(1);
    query = request_id ? query.eq("id", request_id) : query.eq("request_no", request_no);
    const { data: requests, error } = await query;
    if (error) return errorResult(error.message);
    const request = requests?.[0];
    if (!request) return errorResult("Request not found.");
    const { data: items, error: itemsError } = await client.from("request_items").select("*").eq("request_id", request.id).order("sort_order", { ascending: true }).order("created_at", { ascending: true });
    if (itemsError) return errorResult(itemsError.message);
    return textResult({ request, items: items ?? [] });
  }
});

// src/lib/mcp/tools/list-requirements.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_requirements_default = defineTool4({
  name: "list_requirements",
  title: "List trim chart requirements",
  description: "List trim chart requirement lines (required, received and balance quantities) for a given order.",
  inputSchema: {
    order_id: z4.string().describe("Order id (uuid) whose trim chart should be listed."),
    limit: z4.number().int().optional().describe("Maximum rows to return (default 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("requirements").select("*").eq("order_id", order_id).order("sort_order", { ascending: true }).order("created_at", { ascending: true }).limit(Math.min(limit ?? 200, 500));
    if (error) return errorResult(error.message);
    return textResult({ requirements: data ?? [] });
  }
});

// src/lib/mcp/tools/search-items.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^3.25.76";
var search_items_default = defineTool5({
  name: "search_items",
  title: "Search item catalog",
  description: "Search the item master catalog by item code or description. Use this to find the exact standardized description before referencing an item.",
  inputSchema: {
    search: z5.string().optional().describe("Text to match in item code or description."),
    limit: z5.number().int().optional().describe("Maximum rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let query = supabaseForUser(ctx).from("material_catalog").select("id, item_code, description, uom, created_at").order("description", { ascending: true }).limit(Math.min(limit ?? 50, 200));
    if (search?.trim()) {
      const s = `%${search.trim()}%`;
      query = query.or(`item_code.ilike.${s},description.ilike.${s}`);
    }
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult({ items: data ?? [] });
  }
});

// src/lib/mcp/tools/add-catalog-item.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z6 } from "npm:zod@^3.25.76";
var add_catalog_item_default = defineTool6({
  name: "add_catalog_item",
  title: "Add item to catalog",
  description: "Add a new item (item code, description, unit of measure) to the item master catalog. Search first to avoid duplicates.",
  inputSchema: {
    item_code: z6.string().describe("Item code, e.g. TRM-1042."),
    description: z6.string().describe("Standardized item description."),
    uom: z6.string().optional().describe("Unit of measure, e.g. PCS, MTR, YDS.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ item_code, description, uom }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const client = supabaseForUser(ctx);
    const code = item_code.trim();
    const desc = description.trim();
    if (!code || !desc) return errorResult("item_code and description are required.");
    const { data: existing, error: lookupError } = await client.from("material_catalog").select("id, item_code, description, uom");
    if (lookupError) return errorResult(lookupError.message);
    const norm = (v) => v.trim().toLowerCase().replace(/\s+/g, " ");
    const duplicate = (existing ?? []).find(
      (row) => norm(row.item_code ?? "") === norm(code) && norm(row.description ?? "") === norm(desc)
    );
    if (duplicate) return textResult({ created: false, reason: "duplicate", item: duplicate });
    const { data, error } = await client.from("material_catalog").insert({ item_code: code, description: desc, uom: uom?.trim() || "PCS", created_by: ctx.getUserId() }).select().single();
    if (error) return errorResult(error.message);
    return textResult({ created: true, item: data });
  }
});

// src/lib/mcp/tools/list-delivery-notes.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z7 } from "npm:zod@^3.25.76";
var list_delivery_notes_default = defineTool7({
  name: "list_delivery_notes",
  title: "List delivery notes",
  description: "List delivery acknowledgments (delivery notes). Optionally include their line items or filter by request id.",
  inputSchema: {
    request_id: z7.string().optional().describe("Only delivery notes for this request id."),
    include_items: z7.boolean().optional().describe("Include line items for each note."),
    limit: z7.number().int().optional().describe("Maximum rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ request_id, include_items, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const client = supabaseForUser(ctx);
    let query = client.from("delivery_acknowledgments").select("*").order("created_at", { ascending: false }).limit(Math.min(limit ?? 50, 200));
    if (request_id) query = query.eq("request_id", request_id);
    const { data: notes, error } = await query;
    if (error) return errorResult(error.message);
    if (!include_items) return textResult({ delivery_notes: notes ?? [] });
    const ids = (notes ?? []).map((n) => n.id);
    const { data: items, error: itemsError } = ids.length ? await client.from("delivery_items").select("*").in("acknowledgment_id", ids) : { data: [], error: null };
    if (itemsError) return errorResult(itemsError.message);
    return textResult({
      delivery_notes: (notes ?? []).map((n) => ({
        ...n,
        items: (items ?? []).filter((i) => i.acknowledgment_id === n.id)
      }))
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "howbucpdnhanjctztajx";
var mcp_default = defineMcp({
  name: "ghoush-stock-management",
  title: "GHOUSH - Stock Management",
  version: "0.1.0",
  instructions: "Tools for GHOUSH stock management. Read production orders, trim chart requirements, material requests (with approval status and TR numbers), delivery notes, and the item master catalog. Always search the item catalog for the standardized description and item code before referencing an item; new items can be added with add_catalog_item.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_orders_default,
    list_requests_default,
    get_request_default,
    list_requirements_default,
    list_delivery_notes_default,
    search_items_default,
    add_catalog_item_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
